name: culverts
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.2.0=h57928b3_1
  - adal=1.2.7=pyhd8ed1ab_0
  - adlfs=2024.12.0=pyhd8ed1ab_0
  - affine=2.4.0=pyhd8ed1ab_0
  - aiobotocore=2.15.1=pyhd8ed1ab_0
  - aiodns=3.0.0=pyhd8ed1ab_0
  - aiofiles=24.1.0=pyhd8ed1ab_1
  - aiohttp=3.9.5=py312he70551f_0
  - aiohttp-client-cache=0.12.3=pyhd8ed1ab_0
  - aioitertools=0.12.0=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - aiosqlite=0.20.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - anyio=4.4.0=pyhd8ed1ab_0
  - aom=3.9.1=he0c23c2_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312he70551f_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asciitree=0.3.3=py_2
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-retriever=0.19.3=pyha770c72_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.8.6=h0855a55_4
  - aws-c-cal=0.8.7=ha758494_0
  - aws-c-common=0.12.0=h2466b09_0
  - aws-c-compression=0.3.1=ha758494_2
  - aws-c-event-stream=0.5.4=he38e90d_2
  - aws-c-http=0.9.4=h9352bcf_4
  - aws-c-io=0.17.0=ha1a8d55_6
  - aws-c-mqtt=0.12.2=h92a58f8_2
  - aws-c-s3=0.7.13=h1a6e373_2
  - aws-c-sdkutils=0.2.3=ha758494_2
  - aws-checksums=0.2.3=ha758494_2
  - aws-crt-cpp=0.31.0=h91694c7_4
  - aws-sdk-cpp=1.11.510=h2bfe9dd_3
  - azure-core=1.30.2=pyhd8ed1ab_0
  - azure-core-cpp=1.14.0=haf5610f_0
  - azure-datalake-store=0.0.53=pyhd8ed1ab_0
  - azure-identity=1.17.1=pyhd8ed1ab_0
  - azure-identity-cpp=1.10.0=hd6deed7_0
  - azure-storage-blob=12.22.0=pyhd8ed1ab_0
  - azure-storage-blobs-cpp=12.13.0=h3241184_1
  - azure-storage-common-cpp=12.8.0=hd6deed7_1
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.6=hfd34d9b_1
  - bokeh=3.5.1=pyhd8ed1ab_0
  - boltons=24.0.0=pyhd8ed1ab_0
  - botocore=1.35.23=pyge310_1234567_0
  - bottleneck=1.4.0=py312h1a27103_1
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - brotli-python=1.1.0=py312h53d5487_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.4=h2466b09_0
  - ca-certificates=2025.4.26=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - capnproto=1.0.2=hb5d7e06_3
  - cartopy=0.23.0=py312h72972c8_1
  - cattrs=23.2.3=pyhd8ed1ab_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cf_xarray=0.9.4=pyhd8ed1ab_0
  - cffi=1.16.0=py312he70551f_0
  - cfitsio=4.6.2=h2b45a09_0
  - cftime=1.6.4=py312h1a27103_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.1.0=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contextily=1.6.1=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h0d7def4_0
  - crc32c=2.7.1=py312h4389bb4_1
  - cryptography=43.0.0=py312h9500af3_0
  - cuda-cccl_win-64=12.6.77=h57928b3_0
  - cuda-cudart-dev_win-64=12.6.77=he0c23c2_0
  - cuda-cudart-static_win-64=12.6.77=he0c23c2_0
  - cuda-cudart_win-64=12.6.77=he0c23c2_0
  - cuda-nvrtc=12.6.77=he0c23c2_0
  - cuda-version=12.6=h7480c83_3
  - cupy=13.3.0=py312h584ea29_2
  - cupy-core=13.3.0=py312h2a51dd3_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.3=py312he70551f_0
  - dask=2024.8.1=pyhd8ed1ab_0
  - dask-core=2024.8.1=pyhd8ed1ab_0
  - dask-expr=1.1.11=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dataretrieval=1.0.11=pyhd8ed1ab_0
  - datashader=0.16.3=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.2=py312h275cf98_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - distributed=2024.8.1=pyhd8ed1ab_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.7.0=he0c23c2_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fastrlock=0.8.2=py312h53d5487_2
  - filelock=3.15.4=pyhd8ed1ab_0
  - fiona=1.10.1=py312h6e88f47_3
  - flexcache=0.3=pyhd8ed1ab_0
  - flexparser=0.4=pyhd8ed1ab_1
  - fmt=11.0.2=h7f575de_0
  - folium=0.17.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py312h4389bb4_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hdaf720e_2
  - freexl=2.0.0=h8276f4a_0
  - frozenlist=1.4.1=py312he70551f_0
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - gdal=3.10.3=py312h275c25d_9
  - geographiclib=2.0=pyhd8ed1ab_0
  - geopandas=1.0.1=pyhd8ed1ab_1
  - geopandas-base=1.0.1=pyha770c72_1
  - geopy=2.4.1=pyhd8ed1ab_1
  - geos=3.13.1=h9ea8674_0
  - geotiff=1.7.4=h86c3423_2
  - glib=2.82.2=h3d4babf_1
  - glib-tools=2.82.2=h4394cf3_1
  - gst-plugins-base=1.24.7=hb0a98b8_0
  - gstreamer=1.24.7=h5006eae_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5netcdf=1.3.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py312h4e244af_101
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.6=nompi_hd5d9e70_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - htmlmin=0.1.12=pyhca7485f_2
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hydrofunctions=0.2.4=pyhd8ed1ab_0
  - hydrosignatures=0.19.3=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - intel-openmp=2024.2.0=h57928b3_980
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.26.0=pyh7428d3b_0
  - ipywidgets=8.1.3=pyhd8ed1ab_0
  - isodate=0.6.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpickle=3.2.2=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h2e8e312_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h2e8e312_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.11=pyhd8ed1ab_0
  - kealib=1.6.2=h9df79d9_0
  - kerchunk=0.2.6=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py312h0d7def4_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20250127.0=cxx17_h4eb7d71_0
  - libaec=1.1.3=h63175ca_0
  - libarchive=3.7.7=h979ed78_3
  - libarrow=19.0.1=h8be2d54_4_cuda
  - libarrow-acero=19.0.1=h7d8d6a5_4_cuda
  - libarrow-dataset=19.0.1=h7d8d6a5_4_cuda
  - libarrow-substrait=19.0.1=hb76e781_4_cuda
  - libavif16=1.2.0=h62bbbde_1
  - libblas=3.9.0=23_win64_mkl
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=23_win64_mkl
  - libclang13=18.1.8=default_ha5278ca_1
  - libcrc32c=1.1.2=h0e60522_0
  - libcublas=12.6.3.3=he0c23c2_1
  - libcufft=11.3.0.4=he0c23c2_0
  - libcurand=10.3.7.77=he0c23c2_0
  - libcurl=8.13.0=h88aaa65_0
  - libcusolver=11.7.1.2=he0c23c2_0
  - libcusparse=12.5.4.2=he0c23c2_0
  - libde265=1.0.15=h91493d7_0
  - libdeflate=1.23=h9062f6e_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libgdal=3.10.3=hc25ceda_9
  - libgdal-core=3.10.3=h36da5af_5
  - libgdal-fits=3.10.3=h6ffb003_5
  - libgdal-grib=3.10.3=hbfaa95b_5
  - libgdal-hdf4=3.10.3=h95c155c_5
  - libgdal-hdf5=3.10.3=h7fa7d29_5
  - libgdal-jp2openjpeg=3.10.3=h137fd1a_5
  - libgdal-kea=3.10.3=hb7b27b9_5
  - libgdal-netcdf=3.10.3=h7141178_5
  - libgdal-pdf=3.10.3=ha3b3649_5
  - libgdal-pg=3.10.3=hc8f1838_5
  - libgdal-postgisraster=3.10.3=hc8f1838_5
  - libgdal-tiledb=3.10.3=h3a66d27_5
  - libgdal-xls=3.10.3=h2c61a36_5
  - libglib=2.82.2=h7025463_1
  - libgoogle-cloud=2.36.0=hf249c01_1
  - libgoogle-cloud-storage=2.36.0=he5eb982_1
  - libgrpc=1.71.0=h35301be_0
  - libheif=1.19.7=gpl_h2684147_100
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_2
  - libintl-devel=0.22.5=h5728263_2
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libkml=1.3.0=h538826c_1020
  - liblapack=3.9.0=23_win64_mkl
  - liblzma=5.8.1=h2466b09_1
  - liblzma-devel=5.8.1=h2466b09_1
  - libnetcdf=4.9.2=nompi_he045f6b_117
  - libnvjitlink=12.6.77=he0c23c2_1
  - libogg=1.3.5=h2466b09_0
  - libparquet=19.0.1=ha850022_4_cuda
  - libpng=1.6.47=had7236b_0
  - libpq=17.4=h9087029_0
  - libprotobuf=5.29.3=he9d8c4a_0
  - libre2-11=2024.07.02=hd248061_3
  - librttopo=1.1.0=hbfc9ebc_18
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=2.0.0=h5a68840_0
  - libspatialite=5.1.0=h378fb81_14
  - libsqlite=3.49.1=h67fdade_2
  - libssh2=1.11.1=he619c9f_0
  - libthrift=0.21.0=hbe90ef8_0
  - libtiff=4.7.0=h797046b_3
  - libutf8proc=2.10.0=hf9b99b7_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libxcb=1.16=hcd874cb_0
  - libxml2=2.13.8=h442d1da_0
  - libxslt=1.1.39=h3df6e99_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_1
  - llvmlite=0.43.0=py312h1f7db74_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=5.2.2=py312h56c7e3b_0
  - lz4=4.3.3=py312h032eceb_2
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=hcfcfb64_1001
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.7.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py312he70551f_0
  - matplotlib=3.8.4=py312h2e8e312_2
  - matplotlib-base=3.8.4=py312hfee7060_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - matplotlib-scalebar=0.9.0=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - minizip=4.0.6=hb638d1e_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2024.1.0=h66d3029_694
  - mplleaflet=0.0.5=py_4
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msal=1.30.0=pyhd8ed1ab_0
  - msal_extensions=1.1.0=py312h2e8e312_1
  - msgpack-python=1.0.8=py312hd5eb7cc_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.5=py312he70551f_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - narwhals=1.30.0=pyhd8ed1ab_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.4=hd8ed1ab_1
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbconvert-pandoc=7.16.4=hd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nc-time-axis=1.4.1=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - notebook=7.2.1=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.60.0=py312hcccf92d_0
  - numcodecs=0.15.1=py312h72972c8_0
  - numpy=2.0.2=py312h49bc9c5_0
  - openjpeg=2.5.3=h4d64b90_0
  - openpyxl=3.1.4=py312he70551f_0
  - openssl=3.5.0=ha4e3fda_1
  - orc=2.1.1=h35764e3_1
  - orjson=3.10.15=py312h2615798_0
  - osmnx=1.9.3=pyhd8ed1ab_0
  - outcome=1.3.0.post0=pyhd8ed1ab_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - owslib=0.31.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h72972c8_1
  - pandoc=3.3=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - param=2.1.1=pyhff2d567_0
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.44=h3d7b363_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h381445a_1
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=24.0=py312haa95532_0
  - pixman=0.44.2=had0cd8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - planetary-computer=1.0.0=pyhd8ed1ab_1
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - plotly=6.1.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - poppler=24.12.0=heaa0bce_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - portalocker=2.10.1=py312h2e8e312_0
  - postgresql=17.4=h9a933bb_0
  - proj=9.6.0=h4f671f6_1
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - prompt_toolkit=3.0.47=hd8ed1ab_0
  - protobuf=5.29.3=py312h275cf98_0
  - psutil=6.0.0=py312h4389bb4_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py3dep=0.19.0=pyhd8ed1ab_0
  - pyarrow=19.0.1=py312h2e8e312_0
  - pyarrow-core=19.0.1=py312h607bf26_0_cuda
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pycares=4.0.0=py312he70551f_3
  - pycparser=2.22=pyhd8ed1ab_0
  - pyct=0.5.0=pyhd8ed1ab_0
  - pydantic=2.8.2=pyhd8ed1ab_0
  - pydantic-core=2.20.1=py312h2615798_0
  - pydaymet=0.19.3=pyhd8ed1ab_0
  - pygeohydro=0.19.3=pyhd8ed1ab_0
  - pygeoogc=0.19.3=pyhd8ed1ab_0
  - pygeoutils=0.19.5=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pykrige=1.7.2=py312h1a27103_2
  - pynhd=0.19.3=pyhd8ed1ab_0
  - pyogrio=0.10.0=py312h6e88f47_1
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pypdf2=3.0.1=pyhd8ed1ab_1
  - pyproj=3.7.1=py312h5ea471a_1
  - pyqt=5.15.9=py312he09f080_5
  - pyqt5-sip=12.12.2=py312h53d5487_5
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - pystac=1.10.1=pyhd8ed1ab_0
  - pystac-client=0.8.3=pyhd8ed1ab_0
  - python=3.12.4=h889d299_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-dotenv=1.0.1=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-pptx=1.0.2=pyh29332c3_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=306=py312h53d5487_2
  - pywinpty=2.0.13=py312h53d5487_0
  - pyyaml=6.0.1=py312he70551f_1
  - pyzmq=26.0.3=py312hd7027bb_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.8=h264fbc2_26
  - qtconsole-base=5.5.2=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - rasterio=1.4.3=py312ha172ac9_1
  - rav1e=0.6.6=h975169c_2
  - re2=2024.07.02=haf4117d_3
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-cache=1.2.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rioxarray=0.17.0=pyhd8ed1ab_0
  - rpds-py=0.19.1=py312h2615798_0
  - rtree=1.3.0=py312h9e53377_1
  - s3fs=2025.3.2=pyhd8ed1ab_0
  - scikit-learn=1.5.1=py312h816cc57_0
  - scipy=1.13.1=py312h1f4e10d_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - selenium=4.32.0=pyhe01879c_0
  - selenium-manager=4.32.0=h63977a8_0
  - send2trash=1.8.3=pyh5737063_0
  - setuptools=69.5.1=py312haa95532_0
  - shapely=2.0.7=py312h3f81574_1
  - sip=6.7.12=py312h53d5487_0
  - siphon=0.10.0=pyhd8ed1ab_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=h23299a8_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - spdlog=1.15.1=hf4138ee_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.2=py312h1a27103_0
  - svt-av1=3.0.1=he0c23c2_0
  - sympy=1.13.3=pyh04b8f61_4
  - tbb=2021.12.0=hc790b64_3
  - tblib=3.0.0=pyhd8ed1ab_0
  - tenacity=9.0.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tiledb=2.27.2=h0578d8b_3
  - tiny-retriever=0.1.3=pyhd8ed1ab_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4.1=py312h4389bb4_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - trio=0.26.2=py312h2e8e312_1
  - trio-websocket=0.11.1=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - ujson=5.10.0=py312h275cf98_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uriparser=0.9.8=h5a68840_0
  - url-normalize=1.4.3=pyhd8ed1ab_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - vc=14.3=h8a93ad2_20
  - vc14_runtime=14.42.34438=hfd919c2_24
  - vs2015_runtime=14.42.34438=h7142326_24
  - watermark=2.4.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.6.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.43.0=py312haa95532_0
  - whitebox=2.3.5=pyhd8ed1ab_0
  - widgetsnbextension=4.0.11=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - wrapt=1.16.0=py312h4389bb4_1
  - wsproto=1.2.0=pyhd8ed1ab_0
  - x265=3.5=h2d74725_3
  - xarray=2024.7.0=pyhd8ed1ab_0
  - xarray-spatial=0.4.0=pyhd8ed1ab_1
  - xclim=0.56.0=pyhd8ed1ab_0
  - xerces-c=3.2.5=he0c23c2_1
  - xlsxwriter=3.2.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2024.6.0=pyhd8ed1ab_0
  - xz=5.8.1=h208afaa_1
  - xz-tools=5.8.1=h2466b09_1
  - yamale=5.2.1=pyhca7485f_0
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.9.4=py312he70551f_0
  - zarr=3.0.7=pyhd8ed1ab_0
  - zeromq=4.3.5=he1f189c_4
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_1
  - zstandard=0.23.0=py312h4389bb4_1
  - zstd=1.5.7=hbeecb71_1
  - pip:
      - netcdf4==1.7.2
prefix: C:\Users\Public\anaconda1\envs\culverts
